[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "https://www.worldclocks.it.com/*"
  to = "https://worldclocks.it.com/:splat"
  status = 301
  force = true

